-- Create users table
CREATE TABLE IF NOT EXISTS users (
    ID BIGSERIAL PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE
);

-- Create items table
CREATE TABLE IF NOT EXISTS items (
    ID BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    IMG_PATH VARCHAR(255),
    PRICE BIGINT NOT NULL
);

-- Create cart_items table
CREATE TABLE IF NOT EXISTS cart_items (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    ITEM_ID BIGINT NOT NULL,
    COUNT INTEGER NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES users(ID) ON DELETE CASCADE,
    FOREIGN KEY (ITEM_ID) REFERENCES items(ID) ON DELETE CASCADE,
    UNIQUE (USER_ID, ITEM_ID)
);

-- Create orders table
CREATE TABLE IF NOT EXISTS orders (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    TOTAL_SUM BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES users(ID) ON DELETE CASCADE
);

-- Create order_items table
CREATE TABLE IF NOT EXISTS order_items (
    ID BIGSERIAL PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    ITEM_ID BIGINT NOT NULL,
    COUNT INTEGER NOT NULL,
    PRICE BIGINT NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES orders(ID) ON DELETE CASCADE,
    FOREIGN KEY (ITEM_ID) REFERENCES items(ID) ON DELETE CASCADE
);

