spring.application.name=payment-service

# Server Configuration
server.port=8081

# Payment Service Configuration
payment.initial-balance=1000000

# OAuth2 Resource Server Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://auth-server:9000

# Logging
logging.level.ru.practicum.market.payment=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=DEBUG

